### ISSUE TITLE
Function Return Values Not Working On Windows.

### ISSUE THREAD

**Issue by ghost** [Napam/meny#9]
```
from meny import menu

def returnsOne():
     def returnsOne():
         return "1"
     menu(locals())
     return 1

def returnsTwo():
     return "Hello World"

returns = menu(locals(), return_mode="flat") # Assume we have entered all cases and returned
print(menu)
```
returnsTwo() function doesn't return "Hello World" It returns 2 instead.

ran with python main.py

**Comment by Napam** [comment]
Hi, and thanks for the feedback!

I just tried the code on Windows 11 with Python 3.10.5 and meny 1.0.3. And my result was
```
PS C:\Users\naphata\repos> python .\main.py
{'returnsOne': 1, 'returnsTwo': 'Hello World'}
```

What kind of versions are you using? Could there be some unexpected behavior when you tried to save the file maybe?

**Comment by ghost** [comment]
when i hit enter it just wont return anything.
https://user-images.githubusercontent.com/16824301/184559201-d96c5d8e-edc5-4899-9a78-1dafee116395.mp4

I'm on Windows 11 with Python 3.10.5 and meny 1.0.3 windows-curses-2.3.0
Manually checked the code in notepad and the code is there saved.

**Comment by Napam** [comment]
Oh ok, the issue is arguably just bad design on my part😅 use backspace to remove the "2" such that the input field is empty, then press enter. When you give an empty it will return.

**Comment by ghost** [comment]
if I remove the 2  it deselects the option so i have to select it again.

whenever i select an option it inputs it's position into the console.

**Comment by Napam** [comment]
It doesn't actually deselect the option per se. The code actually defined a nested menu so when you enter nothing it will go back to the parent menu. If you keep entering nothing you will eventually exit the menu.

Here is something you can do to make it return:
```
1. Run the program
2. Select option two
3. Remove the "2" and press enter
```
Alternatively you can pass the `q` (where the "2" is) to completely exit the nested menus.

To achieve an alternative behavior you could supply the `once` flag:
```python
from meny import menu

def returnsOne():
     def returnsOne():
         return "1"
     menu(locals(), once=True)
     return 1

def returnsTwo():
     return "Hello World"

returns = menu(locals(), return_mode="flat", once=True) # Assume we have entered all cases and returned
print(returns)
```
The once flag will exit the menus after they are ran once (opposed to repeating). 

If it is still unclear I could maybe make a little tutorial if you would like :)

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/16824301/184695972-bbbc518d-ddf5-4f1b-9570-1cba78b4daa2.mp4

Nothing returned 
returns = menu(locals(),frontend="simple", return_mode="tree")

**Comment by Napam** [comment]
Can you try this?:


https://user-images.githubusercontent.com/47104226/184701420-3e8846e9-e92e-4bb8-9372-265aa55116e1.mp4

EDIT: Fixed video encoding

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/16824301/184708827-17150ea5-065a-4ad6-856f-89be9b58dd9b.mp4

Keep in mind this is in frontend="simple" mode. When it's in other modes such as "auto" nothing will be displayed when menu exits.

**Comment by Napam** [comment]
Are you doing a print(return) like I am doing in my video? (I am also using the simple frontend in my video)

**Comment by ghost** [comment]
> Are you doing a print(return) like I am doing in my video? (I am also using the simple frontend in my video)


Sorry. Didnt add print(returns) will test now.
Your on linux im on windows.

**Comment by Napam** [comment]
I am actually using windows in my video, i am using powershell in windows terminal :)

**Comment by ghost** [comment]
> 

Nice will test now. and reply back.

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/16824301/184710861-f4935dd2-e419-428a-9eb5-35c98d74dd26.mp4

It worked now it returns when i exit menu.
Is it possible to get return values without exiting menu?

**Comment by Napam** [comment]
You cannot really do anything with the return values in within the same menu instance, however you can start another menu instance that uses the previous return values:

```python
import meny
from time import sleep

@meny.title("Enter name")
def getName(name: str = "Gary"):
    return name

@meny.title("Enter age")
def getAge(age: int = 42):
    return age

returns = meny.menu([getName, getAge])
name = returns["getName"]
age = returns["getAge"]

@meny.title("I want to be greeted")
def greet():
    print(f"Hello {age} years old {name}")
    sleep(2)

@meny.title("I want to be flattered")
def flatter():
    print(f"Oh {name} (age {age}) you are so funny!")
    sleep(2)

meny.menu([greet, flatter], title=f"Hello {name}, what do you wish for?")

print(f"Goodbye {name}")
```
https://user-images.githubusercontent.com/47104226/184723364-266d945c-db90-4a34-9b5f-f3015b7a2ca7.mp4

A way to pass values between menu choices as you use them is to have a shared state. You can achieve that with a list for example:
```python
import meny
from time import sleep

things = []

def add(thing = None):
    if thing is None:
        return
    things.append(thing)


def pop():
    if things:
        things.pop()

def printThings():
    print(things)
    sleep(2)

meny.menu(locals())
```

https://user-images.githubusercontent.com/47104226/184724846-145b536a-3287-4ddc-a44c-4ac862641ff1.mp4

**Comment by ghost** [comment]
That's  actually cool. I like the concept.
Anyways thanks for the help.

Keep up the good work.

**Comment by Napam** [comment]
Thank you! I updated my answer with another way of doing things :)
